# Input topics handled/muxed.
# For each topic:
# - name    : name identifier to select the topic
# - topic   : input topic of geometry_msgs::Twist type
# - timeout : timeout in seconds to start discarding old messages, and use 0.0 speed instead
# - priority: priority in the range [0, 255]; the higher the more priority over other topics

topics:
-
  name    : iLQR
  topic   : cmd_vel
  timeout : 0.2
  priority: 10
-
  name    : joystick
  topic   : joy_vel
  timeout : 1.0
  priority: 100


