# TrajClient params
T_horizon: 150
X_des: [8.000000,0.300000,0.000000,0.000000,0.000000,0.000000]
timestep: 0.02

# Rampup params
kp_ramp: 0.45
kd_ramp: 0.05
ki_ramp: 0.1
accel_ramp: 3
target_vel_ramp: 3
timeout_ramp: 2.5

# iLQR params
timeout_ilqr_mpc: 5
stop_goal_threshold: 0.3

ilqr_tolFun: 0.0000001
ilqr_tolConstraint: 0.0000001
ilqr_tolGrad: 0.00001
ilqr_max_iter: 20
ilqr_regType: 1
ilqr_debug_level: 2

init_control_seq: [1.174193,0.055708,1.248933,0.183460,1.309736,0.254257,1.374415,0.286649,1.443472,0.289302,1.518041,0.271520,1.595755,0.244312,1.675894,0.209862,1.756140,0.175674,1.836048,0.144162,1.916031,0.109844,1.994173,0.085356,2.072706,0.053033,2.149441,0.029936,2.225609,0.003226,2.300039,-0.019605,2.372747,-0.044613,2.442675,-0.069143,2.509145,-0.093064,2.571018,-0.115424,2.627222,-0.135077,2.678481,-0.150427,2.726821,-0.159314,2.776217,-0.159720,2.829924,-0.151330,2.888434,-0.136075,2.950544,-0.117379,3.014373,-0.098732,3.078449,-0.082454,3.142067,-0.068969,3.205054,-0.057762,3.267330,-0.048239,3.328902,-0.040001,3.389726,-0.032823,3.449780,-0.026577,3.509058,-0.021170,3.567498,-0.016520,3.625180,-0.012550,3.682042,-0.009193,3.738112,-0.006403,3.793369,-0.004143,3.847645,-0.002381,3.900310,-0.001098,3.949128,-0.000292,3.986722,0.000115,3.989811,0.000364,3.991552,0.000875,3.992447,0.001952,3.991552,0.001446,3.990359,-0.006159,3.991725,-0.015553,3.993516,0.003842,3.993761,0.049081,3.987642,0.081138,2.968727,0.097343,2.319276,0.102315,1.829888,0.092017,1.458542,0.063582,1.176017,0.009948,0.959256,-0.063457,0.790141,-0.138352,0.654861,-0.202522,0.544215,-0.250208,0.451615,-0.279101,0.372911,-0.286719,0.306148,-0.269467,0.250214,-0.227961,0.204478,-0.174012,0.168038,-0.117926,0.139685,-0.065937,0.117909,-0.022462,0.101203,0.009816,0.088358,0.029466,0.078084,0.036639,0.069512,0.032392,0.062278,0.020768,0.056453,0.008096,0.051707,-0.003388,0.047831,-0.011741,0.045239,-0.016218,0.044035,-0.017668,0.043521,-0.017153,0.043525,-0.015640,0.044499,-0.013968,0.045763,-0.012600,0.045916,-0.011660,0.046909,-0.011270,0.048976,-0.011375,0.050028,-0.011545,0.050595,-0.011574,0.052087,-0.010794,0.055154,-0.010366,0.058932,-0.009684,0.063328,-0.007698,0.069192,-0.004942,0.077788,-0.004333,0.088884,-0.002934,0.101633,-0.003858,0.110502,-0.002399,0.119953,-0.003047,0.127768,-0.002579,0.137611,-0.001847,0.149345,-0.003547,0.164937,-0.000956,0.188628,-0.004216,0.209699,-0.000165,0.244595,-0.004010,0.278586,0.001459,0.317184,-0.002541,0.357377,0.004282,0.392596,-0.001818,0.448078,-0.000154,0.487275,-0.039984,0.586722,-0.016733,0.697785,-0.021459,0.827789,-0.019446,0.971307,-0.010156,1.012521,-0.013293,0.914771,-0.001999,0.712229,0.035095,0.549999,0.066759,0.425692,0.030337,0.331435,0.029703,0.260336,-0.015648,0.203259,-0.051326,0.159423,-0.050051,0.126495,-0.056797,0.102677,-0.057340,0.085497,-0.077306,0.073543,-0.086224,0.059687,-0.081271,0.050062,-0.073401,0.045892,-0.053595,0.100463,-0.232815,0.124696,-0.442191,0.122245,-0.619337,0.077929,-0.476380,0.134421,-0.390702,0.224834,-0.325876,0.238695,-0.260377,0.199499,-0.178239,0.147455,-0.077147,0.120827,-0.073704,0.075417,-0.032269,0.038055,0.003762,0.034514,-0.036814,0.021324,-0.084826,0.000884,-0.089189,0.000000,-0.044035,0.089357,-0.063107]

Opt_car_param: {g: 9.81, m: 2.35, L: 0.257, b: 0.14328,
                c_x: 116, c_a: 197, Iz: 0.025, mu: 1.31, mu_s: 0.55,
                limThr: [0, 4.0], limSteer: [-0.68, 0.76]}
Opt_cost: {cu: [0.01, 0.01], cdu: [1.0, 1.5],
           cf: [10, 10, 5, 10, 0.1, 0.1],
           pf: [0.01, 0.01, 0.1, 0.1, 0.1, 0.1],
           cx: [0.05, 0.05, 0.04], cdx: [0.001, 0.005, 0.002],
           px: [0.01, 0.01, 0.1],
           cdrift: -0.001,
           k_pos: 0.5, k_vel: 0, d_thres: 0.3}

######
# TrajServer params
old_msg_discard_thres: 0.5

# Obstacle detection params
scan_clip_angle: 0.35 #radians
naive_obstacle_dist_thres: 1.5
naive_obstacle_percent_thres: 0.2
