# TrajClient params
T_horizon: 150
X_des: [8.000000,0.300000,0.000000,0.000000,0.000000,0.000000]
timestep: 0.02

# Rampup params
kp_ramp: 0.45
kd_ramp: 0.05
ki_ramp: 0.1
accel_ramp: 3
target_vel_ramp: 3
timeout_ramp: 2.5

# iLQR params
timeout_ilqr_mpc: 5
stop_goal_threshold: 0.3

ilqr_tolFun: 0.0000001
ilqr_tolConstraint: 0.0000001
ilqr_tolGrad: 0.00001
ilqr_max_iter: 20
ilqr_regType: 1
ilqr_debug_level: 2

init_control_seq: [2.235736,0.095096,2.316402,0.173573,2.357057,0.222837,2.389908,0.245745,2.428481,0.246454,2.477641,0.229246,2.537130,0.198383,2.604177,0.158661,2.675166,0.110530,2.746395,0.054972,2.813908,-0.003314,2.874372,-0.062739,2.925272,-0.115892,2.963513,-0.157423,2.987178,-0.186155,2.999449,-0.202537,3.008774,-0.206930,3.022971,-0.200174,3.045300,-0.184336,3.075783,-0.162566,3.112964,-0.138688,3.154606,-0.116112,3.198347,-0.096349,3.242365,-0.079316,3.285808,-0.064257,3.328494,-0.050562,3.370442,-0.038052,3.411685,-0.026821,3.452270,-0.017053,3.492290,-0.009040,3.531880,-0.003039,3.571193,0.001446,3.610401,0.005317,3.649684,0.008880,3.689208,0.011995,3.729115,0.014515,3.769509,0.016400,3.810418,0.017673,3.851692,0.018388,3.892794,0.018599,3.932336,0.018302,3.967070,0.017257,3.989708,0.014765,3.997506,0.010041,3.999112,0.008434,3.999402,0.029274,3.999796,0.063090,4.000000,0.079408,3.780712,0.063557,2.952296,0.041920,2.300686,0.018533,1.788016,-0.008462,1.387593,-0.032619,1.076796,-0.049976,0.835750,-0.059100,0.648842,-0.061585,0.503937,-0.059262,0.391613,-0.054174,0.304552,-0.048106,0.237076,-0.042313,0.184773,-0.037456,0.144224,-0.033674,0.112773,-0.030818,0.088366,-0.028660,0.069407,-0.026996,0.054666,-0.025665,0.043186,-0.024545,0.034231,-0.023550,0.027230,-0.022622,0.021742,-0.021721,0.017427,-0.020820,0.014023,-0.019906,0.011328,-0.018971,0.009184,-0.018006,0.007472,-0.017042,0.006098,-0.016008,0.004990,-0.015060,0.004092,-0.013915,0.003362,-0.013122,0.002762,-0.011743,0.002273,-0.011351,0.001864,-0.009586,0.001532,-0.009777,0.001249,-0.007769,0.001022,-0.008358,0.000826,-0.005907,0.000673,-0.006575,0.000536,-0.003511,0.000432,-0.007660,0.000335,-0.007664,0.000264,-0.002234,0.000204,-0.004190,0.000158,-0.002145,0.000121,-0.002538,0.000092,-0.001831,0.000070,-0.001810,0.000052,-0.001467,0.000038,-0.001431,0.000028,-0.001262,0.000020,-0.001170,0.000013,-0.001890,0.000008,0.000237,0.000006,-0.006663,0.000002,0.004766,0.000005,-0.009373,0.000001,0.009216,0.000008,-0.006333,0.000005,0.015050,0.000018,0.005508,0.000028,0.034117,0.000084,0.029625,0.000000,0.121749,0.000001,0.169077,0.000006,-0.008880,0.000041,-0.161928,0.000982,-0.293722,0.001631,-0.357322,0.000667,-0.164370,0.000437,0.003005,0.000948,0.147403,0.001192,0.190355,0.001884,0.147896,0.002729,0.103733,0.003978,0.086479,0.005751,0.062631,0.007987,0.051117,0.009838,0.035266,0.009381,0.026233,0.010680,0.019985,0.000394,0.016884,0.000839,-0.049876,0.059694,-0.019850,0.000797,0.024511,0.000000,0.015172,0.006301,-0.006917,0.000000,0.004409,0.000000,-0.007773,0.000000,-0.000758,0.000000,0.001374,0.000000,0.003175,0.000017,0.001625,0.000000,0.002087,0.000411,-0.000513,0.000297,0.001426,0.003099,0.000427,0.001042,0.004927,0.000000,0.002613,0.000000,0.003531,0.000000,0.000606,0.305796,0.012637]

Opt_car_param: {g: 9.81, m: 2.35, L: 0.257, b: 0.14328,
                c_x: 116, c_a: 197, Iz: 0.025, mu: 1.31, mu_s: 0.55,
                limThr: [0, 4.0], limSteer: [-0.68, 0.76]}
Opt_cost: {cu: [0.01, 0.01], cdu: [1.0, 1.5],
           cf: [10, 10, 5, 10, 0.1, 0.1],
           pf: [0.01, 0.01, 0.1, 0.1, 0.1, 0.1],
           cx: [0.05, 0.05, 0.04], cdx: [0.001, 0.005, 0.002],
           px: [0.01, 0.01, 0.1],
           cdrift: -0.001,
           k_pos: 0.5, k_vel: 0, d_thres: 0.3}

######
# TrajServer params
old_msg_discard_thres: 0.5

# Obstacle detection params
scan_clip_angle: 0.35 #radians
naive_obstacle_dist_thres: 1.5
naive_obstacle_percent_thres: 0.2
